version: "3.8"

services:
  student_perf:
    build: .
    container_name: student_perf_container
    ports:
      - "5001:5001"  
      - "5000:5000"  
    volumes:
      - .:/app
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    command: >
      sh -c "
        echo 'Pulling DVC data...' &&
        dvc pull &&
        echo 'Starting MLflow UI...' &&
        mlflow ui --host 0.0.0.0 --port 5000 &
        echo 'Starting Flask API...' &&
        python api/dvc_mlflow_app.py --port 5001
      "
