name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image (no push yet)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: false
          tags: dicksonml/student-perf-app:latest

      
     
      # Unit / API tests
     
      - name: Run container for testing
        run: docker run -d --rm --name test_student_api dicksonml/student-perf-app:latest

      - name: Run tests
        run: pytest tests/ --disable-warnings -q

      - name: Show container logs on failure
        if: failure()
        run: docker logs test_student_api || true

      - name: Stop container
        if: always()
        run: docker stop test_student_api || true

      # ----------------------------
      # Push image (only if everything passed)
      # ----------------------------
      - name: Push to DockerHub
        if: success()
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: dicksonml/student-perf-app:latest
