name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Build Docker image (don’t push yet)
      - name: Build Docker image
        run: docker build -t dicksonml/student-perf-app:latest .

      # 5. Run container
      - name: Run container
        run: |
          docker run -d -p 5002:5002 --name student-perf-app dicksonml/student-perf-app:latest
          echo "Waiting for API to be ready..."
          sleep 20

      # 6. Install test dependencies
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests

      # 7. Run tests
      - name: Run tests
        run: pytest tests/ --disable-warnings -q

      # 8. Push image only if tests pass
      - name: Push Docker image
        if: success()
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: dicksonml/student-perf-app:latest

      # 9. Show container logs on failure
      - name: Show container logs on failure
        if: failure()
        run: docker logs student-perf-app || true
