name: CI - Student Performance API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest requests

      - name: Build Docker image
        run: docker build -t dicksonml/student-perf-app:latest .

      - name: Run tests
        run: pytest -v --maxfail=1 --disable-warnings

      - name: Cleanup Docker (always runs)
        if: always()
        run: |
          docker ps -aq --filter "name=test_student_api" | xargs -r docker rm -f
          docker system prune -af --volumes
